export const SET_INPUT = "SET_INPUT";
export const SET_CONVERSATION = "SET_CONVERSATION";
export const SET_WATSON_RESPONSE = "SET_WATSON_RESPONSE";
export const PRINT_USER_DIALOG = "PRINT_USER_DIALOG";
export const PRINT_BOT_DIALOG = "PRINT_BOT_DIALOG";